openapi: 3.0.1
info:
  title: Worker Service
  description: Worker Service API
  version: "1"
servers:
  - url: https://localhost/v1
  - url: http://localhost/v1
tags:
  - name: Worker API's
    description: Worker api's
paths:
  /worker/hello:
    get:
      tags:
        - Worker API's
      description: Hello world example.
      operationId: helloAPI
      responses:
        200:
          description: Successful
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HelloWorldResponse'
components:
  schemas:
    HelloWorldResponse:
      required:
        - message
      type: object
      properties:
        message:
          title: "Message"
          type: string
          description: The message
          example: "Hello World!"