replicaCount: 1

image:
  repository: 096987977627.dkr.ecr.eu-west-1.amazonaws.com/api/worker-service
  tag: latest
  pullPolicy: Always

nameOverride: "worker-service"
fullnameOverride: "worker-service"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  paths:
    - /api/v1/worker

aws:
  role: service-default-role

appdynamics:
  appdynamics_controller_host_name: null
  appdynamics_agent_account_name: null
  appdynamics_agent_account_access_key: null
  appdynamics_agent_application_name: api-dev
  appdynamics_java_agent_reuse_node_name: True
  appdynamics_controller_port: 443
  appdynamics_controller_ssl_enabled: True

env:
  db_host: sqlserver.sqlserver.svc
  db_name: neo_service_worker
  db_password: null
  db_username: null
  activemq:
    broker_url: vm://localhost?broker.persistent=false,useShutdownHook=false
    user: admin
    password: admin
  container:
    ingress:
      neo:
        service:
          trigger: http://trigger-service.trigger-service.svc:8080
  spring:
    profiles:
        active: dev
